name: foobar2000
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: foobar2000 is an advanced freeware audio player.
description: |
 Features
   *Supported audio formats are MP3, MP4, AAC, CD Audio, WMA, Vorbis, Opus, FLAC, WavPack, WAV, AIFF, Musepack, Speex, AU, SND... and more with additional components.
   *Gapless playback.
   *Easily customizable user interface layout.
   *Advanced tagging capabilities.
   *Support for ripping Audio CDs as well as transcoding all supported audio formats using the Converter component.
   *Full ReplayGain support.
   *Customizable keyboard shortcuts.
   *Open component architecture allowing third-party developers to extend functionality of the player.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
    run-on: [amd64, i386]

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-i386

apps:
  foobar2000:
    command: foobar2000
    desktop: usr/share/applications/foobar2000.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, pulseaudio, hardware-observe, process-control, cups-control, removable-media, wine-platform-plug ]

parts:
  foobar2000:
    plugin: nil
    source: ./scripts
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget http://www.foobar2000.org/download -q -S -O - 2>&1 | grep foobar2000_v | awk '{print $4}'|sed '2,3d;s|v||;s|</a><br||;s|</a>||')
      echo $ver > $SNAPCRAFT_STAGE/version
      ./dl_f2k
    stage:
      - bin
      - usr
      - wine-platform
    build-packages: [wget, icoutils]
